---
# role: ansible-role-podman
# file: tasks/sysctl.yml

- name: Set sysctl config (Archlinux)
  sysctl:
    name: kernel.unprivileged_userns_clone
    value: '1'
    sysctl_file: /etc/sysctl.d/99-kernel-unprivileged-userns.conf
    reload: yes
  when: ansible_os_family == 'Archlinux'

- name: Set sysctl config (Archlinux)
  sysctl:
    name: user.max_user_namespaces
    value: '28633'
    sysctl_file: /etc/sysctl.d/99-userns.conf
    reload: yes
  when: ansible_os_family == 'RedHat'
