---
# role: ansible-role-podman
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  - name: podman-arch
    image: "archlinux/base"
    privileged: True
  - name: podman-centos7
    image: "centos:7"
    privileged: True
    capabilities:
      - SYS_ADMIN
  # - name: podman-suse
  #   image: "opensuse/leap"
  #   privileged: True
  # - name: podman-opensuse
  #   image: "opensuse/tumbleweed"
  #   privileged: True
  - name: podman-ubuntu1804
    image: "ubuntu:18.04"
    privileged: True
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  playbooks:
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        role_podman_enabled: true
        podman_users:
          root: '100000:65535'
        podman_storage_driver: 'vfs'
        podman_storage_mountopt: ''
        podman_conf_cgroup_manager: 'cgroupfs'
        podman_conf_events_logger: 'file'
scenario:
  name: default
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: true
    sudo: false
  lint:
    name: flake8
